name: iris_scoring
channels:
  - defaults
  - conda-forge
dependencies:
  # The python interpreter version.
  # Currently Azure ML Workbench only supports 3.5.2 and later.
  - python=3.8.18
  - pip

  - pip:
      - numpy==1.23.5
      - pandas==2.0.3
      - pytest==7.4.4
      - pytest-cov==4.1.0
      - azureml-sdk==1.55.0
      - azureml-defaults
      - azureml-monitoring
      - black
      - cached-property
      - jsonlines
      - nteract-scrapbook
      - pydocumentdb
      - tqdm
      - pyemd
      - ipywebrtc
      - pre-commit
      - scikit-learn==1.3.2
      - requests
      - requests-oauthlib
      - regex==2023.12.25
      - seaborn==0.13.2
      - joblib==1.3.2