name: iris_scoring
channels:
  - defaults
  - conda-forge
dependencies:
  # The python interpreter version.
  # Currently Azure ML Workbench only supports 3.5.2 and later.
  - python=3.8.18
  - pip

  - pip:
      - scikit-learn
      - pandas
      - numpy
      - pytest
      - pytest-cov
      - azureml-sdk
      - azureml-defaults
      - azureml-monitoring
      - black
      - cached-property
      - jsonlines
      - nteract-scrapbook
      - pydocumentdb
      - tqdm
      - pyemd
      - ipywebrtc
      - pre-commit
      - requests
      - requests-oauthlib
      - regex
      - seaborn
      - joblib