entryScript: artifact-staging/score.py
runtime: python
condaFile: artifact-staging/conda_dependencies.yml
extraDockerfileSteps:
schemaFile:
sourceDirectory: .
enableGpu: False
baseImage:
baseImageRegistry: