name: spam_demo
channels:
  - defaults
  - conda-forge
dependencies:
  # The python interpreter version.
  # Currently Azure ML Workbench only supports 3.5.2 and later.
  - python=3.8.18
  - pip

  - pip:
      - numpy==1.24.4
      - pandas==2.0.3
      - azureml-sdk==1.55.0
      - scikit-learn==1.3.2
      - pyarrow==15.0.0
      - regex==2023.12.25
      - seaborn==0.13.2
      - joblib==1.3.2
