name: spam_demo
channels:
  - defaults
  - conda-forge
dependencies:
  # The python interpreter version.
  # Currently Azure ML Workbench only supports 3.5.2 and later.
  - python=3.8.18
  - pip

  - pip:
      - numpy
      - pandas
      - azureml-sdk
      - scikit-learn
      - pyarrow
      - regex
      - seaborn
      - joblib