name: Azure MLOps Deployment

on:
  push:
    branches:
      - github_actions

env:
  ML_RESOURCE_GROUP: ${{ secrets.ML_RESOURCE_GROUP }}
  ML_WORKSPACE: ${{ secrets.ML_WORKSPACE }}
  ML_REGION: ${{ secrets.ML_REGION }}
  ML_COMPUTE_NAME: ${{ secrets.ML_COMPUTE_NAME }}
  ML_COMPUTE_VM_SIZE: ${{ secrets.ML_COMPUTE_VM_SIZE }}
  ML_COMPUTE_MIN_NODES: ${{ secrets.ML_COMPUTE_MIN_NODES }}
  ML_COMPUTE_MAX_NODES: ${{ secrets.ML_COMPUTE_MAX_NODES }}
  ML_COMPUTE_IDLE_SECS: ${{ secrets.ML_COMPUTE_IDLE_SECS }}
  ML_EXPERIMENT_NAME: ${{ secrets.ML_EXPERIMENT_NAME }}
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  SERVICE_NAME: "spam_classifier"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        architecture: 'x64'

    #- name: Install dependencies
    #  run: |
    #    chmod +x environment_setup/install-requirements.sh
    #    ./environment_setup/install-requirements.sh

    - name: Install Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    - name: Login to Azure
      run: |
        echo "$AZURE_CREDENTIALS" > azure_credentials.json
        az login --service-principal -u $(jq -r .clientId azure_credentials.json) -p $(jq -r .clientSecret azure_credentials.json) --tenant $(jq -r .tenantId azure_credentials.json)

    - name: Install Azure ML extension
      run: |
        az extension add -n azure-cli-ml

      # Step 2: Deploy Model to Azure Container Instances
    - name: Deploy SPAM Model
      run: |
        az ml model deploy -g $ML_RESOURCE_GROUP -w $ML_WORKSPACE -n $SERVICE_NAME --model "SPAM:1" --dc deployment/aciDeploymentConfig.yml --ic deployment/inferenceConfig.yml --description "SPAM Classifier deployed in ACI" --overwrite

  test:
    name: Execute Tests
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Run Smoke Tests
      - name: Run Tests with Pytest
        run: |
          python3 -m pytest smoke_tests.py \
            --doctest-modules \
            --junitxml=test-results.xml \
            --cov . \
            --cov-report=xml \
            --cov-report=html \
            --scoreurl $(az ml service show \
              -g ${{ secrets.AZURE_RESOURCE_GROUP }} \
              -w ${{ secrets.AZURE_WORKSPACE_NAME }} \
              -n ${{ github.event.inputs.service_name }} \
              --query scoringUri -o tsv)

      # Step 3: Publish Test Results
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: spam_classifier/a/tests/smoke/test-results.xml