name: Debug Upload Artifact

on:
  push:
    branches:
      - github_actions

jobs:
  test-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create Test Directory
      run: |
        mkdir test-directory
        echo "This is a test file" > test-directory/test-file.txt

    - name: Upload Test Artifact
      uses: actions/upload-artifact@v3
      with:
        name: test-artifact
        path: test-directory/
