name: Azure MLOps Deployment

on:
  push:
    branches:
      - github_actions

jobs:
  setup:
    name: Set Up Environment
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Use Python 3.8
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      # Step 3: Install Requirements
      - name: Install Requirements
        run: |
          chmod +x environment_setup/install-requirements.sh
          ./environment_setup/install-requirements.sh

      # Step 4: Install Azure CLI and Extensions
      - name: Install Azure CLI and ML Extension
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          az extension add -n azure-cli-ml

  deploy:
    name: Deploy Model to ACI
    runs-on: ubuntu-latest
    needs: setup

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Deploy Model to Azure Container Instances
      - name: Deploy SPAM Model
        run: |
          az ml model deploy \
            -g ${{ secrets.AZURE_RESOURCE_GROUP }} \
            -w ${{ secrets.AZURE_WORKSPACE_NAME }} \
            -n ${{ github.event.inputs.service_name }} \
            -f metadata/model.json \
            --dc deployment/aciDeploymentConfig.yml \
            --ic deployment/inferenceConfig.yml \
            --description "SPAM Classifier deployed in ACI" \
            --overwrite
        working-directory: spam_classifier

  test:
    name: Execute Tests
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Run Smoke Tests
      - name: Run Tests with Pytest
        run: |
          python3 -m pytest smoke_tests.py \
            --doctest-modules \
            --junitxml=test-results.xml \
            --cov . \
            --cov-report=xml \
            --cov-report=html \
            --scoreurl $(az ml service show \
              -g ${{ secrets.AZURE_RESOURCE_GROUP }} \
              -w ${{ secrets.AZURE_WORKSPACE_NAME }} \
              -n ${{ github.event.inputs.service_name }} \
              --query scoringUri -o tsv)
        working-directory: spam_classifier/a/tests/smoke

      # Step 3: Publish Test Results
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: spam_classifier/a/tests/smoke/test-results.xml